app/code/community/Payone/Core/Model/Domain/Protocol/Api.php

redirecturl=https://www.paypal.com/webscr?useraction=commit&cmd=_express-checkout&token=123456789
will be parsed to
redirecturl=https://www.paypal.com/webscr?useraction=
without this fix

Parse values with equal chars in urls

---

app/design/frontend/base/default/template/payone/core/checkout/onepage/init.phtml

We've experienced an error in checkout with the message "Payment method configuration with id "" not found." for some customers. After long time debugging this problem, I've possibly found the reason.
It seemed that the wrapper function for `payment.save` is never called for some customers, so PAYONE functionality is not executed. The form in checkout payment step is not getting validated and hidden fields are not filled with correct data (like the payment config id mentioned in the error message). The customer reaches checkout review though and gets the above error, when clicking on "Buy" (maybe the missing config id can be validated in observer method `importDataBefore` as well).
After changing the JavaScript observer in this file, we didn't get this error again. I do not understand …

Changed JavaScript initialization in checkout

---

app/code/community/Payone/Core/etc/config.xml

If these fields were left blank, the correct working of crucial parts of the payment flow - such as invoicing - were dependent on the translation system. At some points the translation might not be available - which might be the case for some API calls. It is best to leave this field filled up by default, and the most experienced user would then be able to tweak this if needed.

Adding default values to Invoicing Info non-product items (credit memo, shipping, discounts)

---

app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php

This fix removes leading or trailing whitespaces in the XForwardedFor header.

XForwardedFor Header can contain Whitespace.

---

app/code/community/Payone/Core/Helper/Config.php
app/code/community/Payone/Core/Model/Factory.php
app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Abstract.php

* The implementation from `Mage_Tax_Model_Config` will be used instead
* All return type warnings in `Payone_Core_Model_Factory` have been fixed
* The requested changes fix issue #64

Remove function `getShippingTaxClassId` from `Payone_Core_Helper_Config`

---

app/code/community/Payone/Core/Helper/Config.php

When this exception is being thrown the variable `$configId` always contains a value that evaluates with `false` e.g. "0" or "" – So it makes more sense to print the method's name here to better help debugging purposes.

MAGE-319 - Give 'PaymentMethodConfigNotFound' a more meaningful message

---

app/design/adminhtml/default/default/template/payone/core/payment/method/form/creditcard.phtml

- This commit adds missing hidden fields for credit card payments to the template for backend orders. - The absence of these fields caused creditcard.js to crash, when 'hosted iframe' was being used.

[MAGE-321] Fix the backend order form for credit card payments

---

app/code/community/Payone/Core/controllers/Checkout/CartController.php
app/design/frontend/base/default/layout/payone/core.xml
app/design/frontend/base/default/template/payone/core/checkout/cart/helper.phtml

When a user cancels an order by leaving the external payment provider's checkout (e.g. PayPal) using the browser's history navigation ("back"), the shopping cart now displays a corresponding notice and prevents the user from navigating "forward" again.

[MAGE-327] Display a notice and push state to browser history

---

app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/External.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransfer.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferBct.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferEps.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferGiropay.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferIdl.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferP24.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferPostFinanceCard.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferPostFinanceEfinance.php
app/code/community/Payone/Core/Model/Payment/Method/OnlineBankTransferSofortueberweisung.php
app/code/community/Payone/Core/Model/Payment/Method/Wallet.php
app/code/community/Payone/Core/Model/Payment/Method/WalletAliPay.php
app/code/community/Payone/Core/Model/Payment/Method/WalletPaydirekt.php
app/code/community/Payone/Core/Model/Payment/Method/WalletPaypalExpress.php
app/code/community/Payone/Core/controllers/Checkout/CartController.php
app/code/community/Payone/Core/controllers/Checkout/Onepage/PaymentController.php
app/code/community/Payone/Core/etc/config.xml

* Navigation in checkout sessions using an online bank transfer provider will be handled just the same as sessions using a wallet payment provider.
* Any parallel user activity in the shop (e.g. in a second tab/window) during external payment handling results in order cancellation and cart restoration now.

[MAGE-327] Fix browser navigation during checkout

---

app/code/community/Payone/Core/controllers/TransactionStatusController.php

If the order could not be loaded, we should not do anything else in this method.

fixed issue with Shopgate orders

---

app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php

array_shift delivers the first ip, but as the comment says we need the last ip. So array_pop should be used here.

Fixed customer ip

---

app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/MultiplePaymentCheck.php

We're getting PHP notices, because sometimes key "method" does not exist in $paymentData.

Fixed PHP notices

---

app/code/community/Payone/Core/Model/Config/General/StatusMapping.php
app/code/community/Payone/Core/Model/System/Config/Backend/Serialized/Array.php
app/code/community/Payone/Core/etc/config.xml
app/code/community/Payone/Core/etc/system.xml

- Adds the mapping option for rec/POV
- Fix a bug that prevents default mapping values to be read from configuration, after magento 1.9.3

Mage 342 tx status mapping missing rec pov

---

app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php

Fix the walletType recognition to re-enable Paydirekt reference number patch

MAGE-344: Re-enable Paydirekt reference number patch

---

app/code/community/Payone/Core/Model/Service/TransactionStatus/Execute.php

PayOne sends the Transactionstatus Update to the Shop.
But the Table fields "store_id" and "order_id" are "NULL" by default.
While PayOne tries to process the Transaction Status it sets the Store to the Store ID from the Order.
The Problem is that the Store ID does not exists and the Cronjob is running in the Admin Store (ID: 0).
So many Configurations like Sender Mail and others are not fetched correctly. 
They are fetched from the Admin Store instead of the Store to which the Order belongs.
This Update fixes the Problem and fetches the Store ID from the Order by Reference of the IncrementID.
During the Process the Fields "store_id" and "order_id" will be saved to the Table Entry.
But at this point it is to late. The correct Store ID is needed where the Store "emulation" starts not …

Missing Store ID on TransactionStatus Execute

---

app/code/community/Payone/Core/controllers/TransactionStatusController.php

If you are using PAYONE in different systems, trowing an exception bloats your exception log, which makes it harder to analyze. I suggest to just write a warning to a separate log.

No Exception in case of missing order references

---

app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php
app/code/community/Payone/Core/Model/Config/General/PaymentCreditcard.php
app/code/community/Payone/Core/etc/system.xml
app/design/adminhtml/default/default/template/payone/core/system/config/tooltip/general/payment_creditcard.phtml
app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml
app/locale/de_DE/Payone_Core.csv

- Switch fields to present cc number before cc type selection
- implement config option to completely hide the cc type selector

MAGE-382: updates around credit card recognition

---

app/design/frontend/base/default/template/payone/core/mastercard/masterpass/shortcut.phtml

This new line is output no matter if MasterPas is enabled or not. Hence, the condition `$methodHtml = $this->getMethodHtml($method)` in `checkout/cart.phtml` is passed, which leads to an empty `<li>` element when MasterPass is disabled.

removed unnecessary newline

---

app/code/community/Payone/Core/Block/Adminhtml/Transaction/View/Tab/TransactionStatus.php

Open a transaction (`/admin/payonecore_transaction/view/id/123/`), open the transaction status grid on the left side and click any transaction. This currently leads to a 404 page. This PR fixes the issue.

fixed transaction status link from transaction view

---

app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/Methods.php

`getCustomerData` may return `null` (e.g. for `payone_advance_payment`), which leads to an "Invalid argument supplied for foreach()" error, so that the last payment method is not set correctly.

fixed potential bug during payment method restore

---

js/payone/core/creditcard.js

On mobile devices, the CC data form may not be visible if the user clicks the "Continue" button. If there is a CC hosted error, the user cannot continue and maybe the shown error is not in the viewport. Hence, it is a good idea to scroll to the error messag as implemented in this PR.

scroll to error message on CC hosted error

---

app/code/community/Payone/Core/Model/System/Config/Backend/Serialized/Array.php

- some classes used for Unserializing were not introduced yet.

MAGE-425: Fix for magento version < 1.9.2.2

---

js/payone/core/amazonpay.js

IE10 and IE11 do "[...] not support multiple parameters for the add() & remove() methods" (source https://caniuse.com/#feat=classlist), therefore in checkout review step you can't move further after selecting address + shipping method. This will fix it.

Fixed AmazonPay checkout for IE10 + IE11

---

README.md

We created a little extension that allows to disable selected methods when certain products are in the shopping cart. This is necessary to comply with requirements of some payment provides (e.g. when it is not allowed to sell coupons with installment or the like).

Added restrict products extension

---

app/design/adminhtml/default/default/template/payone/core/system/config/form/field/ratepay_shopids.phtml

This change prevents Magento/PHP outputting or logging
> Notice: Undefined variable: aRow  in /var/www/html/app/design/adminhtml/default/default/template/payone/core/system/config/form/field/ratepay_shopids.phtml on line 53

Fixed PHP notice "Undefined variable: aRow"

---

app/code/community/Payone/Core/Helper/Config.php
app/code/community/Payone/Core/Model/Observer/TransactionStatus/InvoiceCreate.php
app/code/community/Payone/Core/Model/Service/InitializeConfig.php
app/code/community/Payone/Core/Model/Service/TransactionStatus/Process.php

This pull-request fixes issues with the Service TransactionStatus Process which run using a Cronjob.
From time to time it can happen, that you get an error message much like this one.
"Payment method configuration with id "18" not found."
This error is thrown in ``Observer_TransactionStatus_InvoiceCreate`` but the root cause is to be found during config initialisation. 
During processing the pending TransactionStatus, the config is first loaded here: \Payone_Core_Model_Service_TransactionStatus_Process::execute:86
In some circumstances the wrong configuration is returned. For example the order is for store-id 2 but the config that is returned is not. The root of the problem seems to be the caching though this pull request will not address any of the caching logic. 
There are no tests and …

introduce cache bypass to fix issues with invalid store configs

---

app/code/community/Payone/Core/Model/Service/InitializeConfig.php

+ Force unregistering a variable before registering a value under the same name.

MAGE-466: add safety during config initialization

---

app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php

Under some circumstances, there is the error "Sorry, your transaction with Amazon Pay was not successful. Please try again." thrown, even if the values seem to be identical. After implementing a logging, we figured out, that there seems to be a comparison between a string and a floating point number, which is not safe anyway. See: https://stackoverflow.com/questions/3148937/compare-floats-in-php
To avoid this, the value is converted to a string before writing the value into the session and to convert both values to the same "number_format" value with 4 digits

MAGE-470: Fix aborted Amazon Pay checkouts

---

app/code/community/Payone/Core/Model/Handler/Cancellation.php

If a post-checkout redirect payment is neither completed nor truly cancelled, use of another browser tab in the shop has all item quantities in the cart doubled.
This issue was found using _online_bank_transfer_p24_ but I believe it can apply to any payment that redirects after completing the checkout, such as Paypal 
to reproduce:
- go to a PDP page and add the product to cart
- open the PDP page in another tab in the same browser
- with either tab complete the magento checkout with a post checkout payment selected (ex: Przelewy24)
- redirect to the payment site, but do not complete the payment yet
- switch to the other tab and continue to shop. The minicart might not reflect this right away, but if you refresh or add another product, all the cart items will have double the original cart …

item qtys doubled when using multi tabs and redirect payments

---

app/code/community/Payone/Core/Helper/Payment/Data.php
app/code/community/Payone/Core/Model/Config/Payment/Method.php
app/code/community/Payone/Core/Model/Config/Payment/Method/Interface.php
app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
app/code/community/Payone/Core/Model/System/Config/PaydirektSecuredPreorderGuaranteePeriod.php
app/code/community/Payone/Core/Model/System/Config/PaymentMethodCode.php
app/code/community/Payone/Core/Model/System/Config/PaymentMethodType.php
app/code/community/Payone/Core/etc/config.xml
app/code/community/Payone/Core/etc/system.xml
app/code/community/Payone/Core/sql/payone_core_setup/mysql4-upgrade-5.3.2-5.3.3.php
app/code/community/Payone/Core/sql/payone_core_setup/upgrade-5.3.2-5.3.3.sql
app/locale/de_DE/Payone_Core.csv
app/locale/en_US/Payone_Core.csv

Add two request parameter and config settings

MAGE-539: Rename Paydirekt
