- app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml
> In CC checkout, first and last name now are truly mandatory fields

- app/code/community/Payone/Core/Model/Config/General/CcHostedTranslations.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
* Fixes #18 where foreach() was called with false as an argument
* Fixes #17 unused argument
> Fix some smaller issues

- app/code/community/Payone/Core/Block/Payment/Method/Form/Payolution.php
> Fix payolution url secure flag

- app/code/community/Payone/Core/etc/config.xml
> Fix array serialization in config.xml

- app/code/community/Payone/Core/etc/config.xml
Not consistent with git version tag on https://github.com/PAYONE-GmbH/magento-1/releases
> Version Bump

- composer.json
> Added modman mapping to composer.json

- app/code/community/Payone/Core/Model/Domain/Customer.php
Just an if for empty customer_date .... 
sadly no unit tests possible because of core helpers
> #37 fix for empty customer_data

- app/code/community/Payone/Core/Block/Payment/Method/Form/Payolution.php
This was affecting Payolution Debit too, which was not supposed to happen.
> MAGE-298 - Isolated the new behaviour to Payolution Installment only

- app/code/community/Payone/Core/controllers/Adminhtml/Payonecore/Protocol/TransactionStatusController.php
- app/code/community/Payone/Core/etc/adminhtml.xml
> MAGE-300 - Fixed admin access control problem

- app/code/community/Payone/Core/sql/payone_core_setup/mysql4-upgrade-3.7.6-3.7.7.php
- app/code/community/Payone/Core/sql/payone_core_setup/upgrade-3.7.6-3.7.7.sql
> MAGE-301 - Fixed problem with faulty SQL update script

- app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php
> MAGE-302 - Integrated code-suggestion of another user

- app/code/community/Payone/Core/Block/Adminhtml/Protocol/TransactionStatus/View.php
- app/code/community/Payone/Core/Model/Repository/TransactionStatus.php
> MAGE-303 - Fixed incomplete raw request and API-log 404 error problem

- app/code/community/Payone/Core/Helper/Data.php
- app/code/community/Payone/Core/Model/Config/Misc/TransactionstatusProcessing.php
- app/code/community/Payone/Core/Model/Cronjob/TransactionStatus/Worker.php
- app/code/community/Payone/Core/Model/Service/TransactionStatus/Execute.php
- app/code/community/Payone/Core/Model/Service/TransactionStatus/Process.php
- app/code/community/Payone/Core/etc/system.xml
- app/locale/de_DE/Payone_Core.csv
For #59
In the admin PAYONE misc config there is now an option for cronjob logging.
The log-file can be found under /var/log/payone_cron.log when activated.
> MAGE-303 - Added logging mode for the TransactionStatus cronjob

- app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/MultiplePaymentCheck.php
The method `performChecks` has been refactored completely to simplify its execution paths, which also improves readability and helps to avoid similar bugs in the future.
> MAGE-313 - Fix a bug in the multiple payment checks observer

- lib/Payone/Api/Request/Parameter/Authorization/PaymentMethod/Barzahlen.php
- lib/Payone/Api/Request/Parameter/Authorization/PaymentMethod/CreditCardIframe.php
- lib/Payone/Api/Request/Parameter/Authorization/PaymentMethod/Payolution.php
- lib/Payone/Api/Request/Parameter/Authorization/PaymentMethod/RatePay.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/Barzahlen.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/CreditcardIframe.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/Payolution.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/PayolutionDebit.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/PayolutionInstallment.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/PayolutionInvoicing.php
- lib/Payone/Settings/Data/ConfigFile/PaymentMethod/Ratepay.php
ISO-8859-1 files to UTF-8 (as the rest of the extension)
> Fix encoding

- app/code/community/Payone/Core/Model/Payment/Method/Abstract.php
Add quote as a possible parameter to getConfigData()
Reviewed in MAGE-315
> Config quote

- lib/Payone/Api/Request/Parameter/Authorization/PaymentMethod/Wallet.php
add two missing parameter to implement recurring payment with paypal
> add parameter for recurring payment

- lib/Payone/Api/Request/Parameter/Authorization/PersonalData.php
This is just a proposed quick & dirty solution to problems currently occurring for some merchants
> MAGE-318 Remove customerid parameter from all authorization requests

- app/code/community/Payone/Core/Model/Handler/Payment/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/controllers/Checkout/CartController.php
- app/code/community/Payone/Core/controllers/Checkout/Onepage/PaymentController.php
* Fixes a bug, that caused a wrong order to be cancelled under circumstances.
> [MAGE-324] Improve handling of external payment providers

- app/code/community/Payone/Core/Controller/Abstract.php
- app/code/community/Payone/Core/Helper/Compatibility.php
- app/code/community/Payone/Core/Model/Factory.php
- app/code/community/Payone/Core/controllers/TransactionStatusController.php
> Do Not Throw OrderNotFound Exception for Shopgate Orders

- app/code/community/Payone/Core/Model/Observer/Sales/Order.php
Maybe it is better to check, whether customer exists before saving the data. Am I right? Also exceptions should be catched here to avoid error messages in frontend.
> Fixed customer save data

- app/code/community/Payone/Core/Model/Payment/Method/Abstract.php
- app/code/community/Payone/Core/Model/Service/Sales/OrderComment.php
- app/locale/de_DE/Payone_Core.csv
Add cancellation support (0-Capture) for Ratepay payment method
- Also changes the capture comment when order is cancelled
> MAGE-336 - Storno auch bei Ratepay Rechnung erlauben

- app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php
2018-02-23T09:01:42+00:00 ERR (3): Notice: Undefined index: agreement  in /var/www/app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php on line 258
> Fix "Undefined index: agreement"

- app/code/community/Payone/Core/Model/Config/Payment/Method.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/etc/config.xml
- app/code/community/Payone/Core/etc/system.xml
- app/code/community/Payone/Core/sql/payone_core_setup/mysql4-upgrade-4.1.2-4.1.3.php
- app/code/community/Payone/Core/sql/payone_core_setup/upgrade-4.1.2-4.1.3.sql
- app/locale/de_DE/Payone_Core.csv
- Adapt the request to add a parameter if overcapture is enabled
- Add the configuration field in database
- Add some translations
> MAGE-337: Add the configuration option to enable Overcapture for Direktpay

- modman
> #175: Add missing modman directive

- app/code/community/Payone/Core/Block/Payment/Method/Form/OnlineBankTransferEps.php
- app/code/community/Payone/Core/Helper/Data.php
- app/code/community/Payone/Core/Model/System/Config/OnlinebanktransferGroups.php
- app/design/frontend/base/default/template/payone/core/payment/method/form/onlinebanktransfer/bankgroupeps.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/onlinebanktransfer/bankgroupidl.phtml
- lib/Payone/Enum/OnlineBankTransferType.php
- refactor the process by exporting the data to a separate file in more practical handling
> MAGE-353: Update bank groups values

- app/locale/de_DE/Payone_Core.csv
> Add missing PayPal Express translations

- app/code/community/Payone/Core/Model/Service/Paypal/Express/Checkout.php
> MAGE-368: Dispatch event after Paypal ECS

- app/code/community/Payone/Core/Block/Mastercard/Masterpass/Review/PaymentMethod.php
- app/code/community/Payone/Core/Block/Mastercard/Masterpass/Shortcut.php
- app/design/frontend/base/default/template/payone/core/mastercard/masterpass/review/payment_method.phtml
- app/design/frontend/base/default/template/payone/core/mastercard/masterpass/shortcut.phtml
- app/locale/de_DE/Payone_Core.csv
- skin/frontend/base/default/payone/core/masterpass.css
- Add separator between Masterpass button and other shortcuts
- Add link to more information close to the button
- Masterpass payement method is shown on review page
> MAGE-373: Update Masterpass solution

- app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php
> MAGE-369: Fix issue when Cart Rules are not always applied with AMZ

- lib/Payone/Api/Response/Abstract.php
- lib/Payone/SessionStatus/Response/Abstract.php
- lib/Payone/SessionStatus/Response/Interface.php
- lib/Payone/SessionStatus/Service/ProtocolRequest.php
- complete a class to prevent future mismatching type errors
> MAGE-379: fix mismatching type Exception

- app/code/community/Payone/Core/controllers/Checkout/Onepage/PaymentController.php
During an redirect checkout it is possible that the customer is redirected to the back or error url.
These methods cancel the Order and reactivate the quote and redirect the customer to the cart.
In the cart the error message is shown and depending on that the customer may take further actions.
Let's say the customer finishes the order the second time and somehow hits the back or error url because it is still in his browser back history.
In this case a totally valid order will be canceled even though it was already appointed.
The Transaction Status that has been sent in the background might not have been processed yet. 
That is the reason why the order->canCancel call will return true, even though the order is valid.
Simple speaking PAYONE sent the information, but the module has not …
> Check for APPOINTED TxStatus before order cancel

- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Genericpayment.php
- app/design/frontend/base/default/template/payone/core/payment/method/form/payolution.phtml
> MAGE-388: Switch company trade number to vat id field

- app/code/community/Payone/Core/Block/Payment/Method/Form/Payolution.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/etc/system.xml
- app/design/adminhtml/default/default/template/payone/core/payment/method/form/payolution.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/payolution.phtml
- adapt block/template
- fix display issue in admin form payolution template
> MAGE-393: Disable B2B Mode for PYD and PYS

- app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/Methods.php
when the method is fetch from customer last used method
Fixes #286
> MAGE-395: Add the payment method config id to the quote 

- app/code/community/Payone/Core/Model/Handler/Cancellation.php
Apparently the [pull request #260](https://github.com/PAYONE-GmbH/magento-1/pull/260) did not fix the issue completely.
As it Turns out there is another logic, which is canceling orders based upon frontend requests.
This cancelation logic is integrated on every checkout/index page call and uses a different basically duplicated logic from the on fixed in the pull request #260.
This pull request adds the TxStatus APPOINTED check to the class ``Payone_Core_Model_Handler_Cancellation``. The check is the same as in the ``Payone/Core/controllers/Checkout/Onepage/PaymentController.php`` from pull request #260 
We are currently testing the solution on a staging environment.
Furthermore if anybody else has this issue, it helps to make sure the payone cron …
> Check for APPOINTED TxStatus before order cancel (2)

- app/code/community/Payone/Core/Model/Service/Paypal/Express/Checkout.php
- app/locale/de_DE/Payone_Core.csv
- add corresponding translation
Fixes #302
> MAGE-403: add a check on data quality in Paypal success/return action

- app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/Methods.php
- into a new quote payment before checkout
> MAGE-395: Add code to copy saved customer fields

- app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml
+ small refactor of a loop to avoid unnecessary process
+ fix another potential similar issue
> MAGE-406: Fix undefined variable error

- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Capture.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php
- only when invoice is available
> MAGE-410: Update the invoice mapping to include invoiceid to each capture

- app/design/adminhtml/default/default/template/payone/core/payment/method/info/debitpayment.phtml
- app/design/adminhtml/default/default/template/payone/core/payment/method/info/onlinebanktransfer.phtml
> MAGE-411: Anonymize IBAN for online bank transfert and debit payment

- app/code/community/Payone/Core/Helper/Config.php
- app/code/community/Payone/Core/Model/Config/General/ParameterInvoice.php
- app/code/community/Payone/Core/Model/Config/Payment/Method.php
- app/code/community/Payone/Core/Model/Config/Payment/Method/Interface.php
- app/code/community/Payone/Core/Model/Domain/Config/PaymentMethod.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Capture.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php
- app/code/community/Payone/Core/Model/Service/InitializeConfig.php
- app/code/community/Payone/Core/etc/config.xml
- app/code/community/Payone/Core/etc/system.xml
- app/design/adminhtml/default/default/template/payone/core/system/config/tooltip/general/parameter_invoice.phtml
- app/locale/de_DE/Payone_Core.csv
- triggered when invoice data transmission occurs
> MAGE-409: Implement alternative price calculation to avoid rounding errors

- app/code/community/Payone/Core/Block/PaymentAdditionalScript.php
- match better the fact that this happens early in checkout
(few information available for extended checks)
> MAGE-426: Refactor payment method JS library loading (simpler)

- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Debit.php
- refactor apirequest classes to move code upward in abstraction level
Fixes #337
> MAGE-424: Add narrative_text parameter to Debit call

- app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php
- js/payone/core/amazonpay.js
+ rework the amazon JS logout usage, putting it back to initial amazon pay implementation logic
> MAGE-434: Fix bug in case confirmOrderRef request was failing

- app/code/community/Payone/Core/Block/Adminhtml/System/Config/Payment.php
- app/design/adminhtml/default/default/template/payone/core/system/config/payment/grid/container.phtml
> Rework payment buttons in backend

- app/design/frontend/base/default/template/payone/core/payment/method/form/payolution.phtml
- js/payone/core/payolution.js
Copy function that extracts dob from select fields to hidden text field to payolution.js to make it independent from ratepay.js. If this is not done and one uses payolution without ratepay the dob will not be collected.
> Copy DOB js function to payoluton.js

- app/code/community/Payone/Core/Block/Adminhtml/System/Config/Payment.php
- app/locale/de_DE/Payone_Core.csv
> Add missing translations

- app/code/community/Payone/Core/sql/payone_core_setup/mysql4-upgrade-4.5.0-4.5.1.php
- app/code/community/Payone/Core/sql/payone_core_setup/upgrade-4.5.0-4.5.1.sql
> MAGE-467: Add indexes on DB tables through sql upgrade

- app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml
for not native-supported languages
> MAGE-468 : Fix to use custom translations in CC hosted-iframes

- app/code/community/Payone/Core/Helper/AmazonPay.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Genericpayment.php
- app/code/community/Payone/Core/Model/Service/Amazon/Pay/Checkout.php
- app/code/community/Payone/Core/controllers/AmazonpayController.php
- lib/Payone/Api/Enum/GenericpaymentAction.php
when the shop can not complete the order after approval
> MAGE-469: Add a cancellation to amazonpay orders

- composer.json
> Noticket: Add missing path to composer.json

- app/code/community/Payone/Core/Helper/Payment/Data.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/design/frontend/base/default/template/payone/core/payment/method/form/safe_invoice/klarna.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/safe_invoice/klarna/scripts.phtml
to avoid collision with Klarna external module
+ fix some buggy code writing
+ add handle to process birthday after safeinvoice-Klarna formular submission
> MAGE-494 : Adapt safeinvoice Klarna code

- app/code/community/Payone/Core/Block/Adminhtml/System/Config/Form/Field/RatePayDirectDebitStoreIds.php
- app/code/community/Payone/Core/Block/Adminhtml/System/Config/Form/Field/RatePayInvoicingStoreIds.php
- app/code/community/Payone/Core/Block/Adminhtml/System/Config/Form/Field/RatePayStoreIds.php
- app/code/community/Payone/Core/Block/Payment/Method/Form/Ratepay.php
- app/code/community/Payone/Core/Block/Payment/Method/Form/RatepayDirectDebit.php
- app/code/community/Payone/Core/Block/Payment/Method/Form/RatepayInvoicing.php
- app/code/community/Payone/Core/Block/Payment/Method/RatepayDeviceFingerprint.php
- app/code/community/Payone/Core/Model/Config/General/PaymentRatepayCheckout.php
- app/code/community/Payone/Core/etc/config.xml
- app/code/community/Payone/Core/etc/system.xml
- app/design/adminhtml/default/default/template/payone/core/system/config/form/field/ratepay_direct_debit_shopids.phtml
- app/design/adminhtml/default/default/template/payone/core/system/config/form/field/ratepay_invoicing_shopids.phtml
- app/design/adminhtml/default/default/template/payone/core/system/config/form/field/ratepay_shopids.phtml
- app/design/frontend/base/default/layout/payone/core.xml
- app/design/frontend/base/default/template/payone/core/payment/method/form/ratepay.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/ratepay_direct_debit.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/ratepay_invoicing.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/ratepay_device_fingerprint.phtml
- app/design/frontend/rwd/default/layout/payone/core.xml
- remove profile specific snippetId handling (config, usage in templates, helping methods)
> MAGE-446: Implement global snippetId configuration field

- app/design/frontend/base/default/template/payone/core/paydirekt/express/review.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/klarna_base.phtml
- js/payone/core/amazonpay.js
- js/payone/core/klarna.js
- js/payone/core/paydirektexpress.js
- skin/frontend/base/default/payone/core/klarna.css
- skin/frontend/base/default/payone/core/paydirektexpress.css
+ in paydirekt checkout
+ in klarna checkout
+ in amazonpay checkout
> MAGE-499 : Adaptation to remove jQuery usages

- app/code/community/Payone/Core/Helper/Data.php
- lib/Payone/Api/Request/Abstract.php
Update the methods for determining the integration params for the systems: Magento and openmage.
> Handle magento and openmage integration params

- app/code/community/Payone/Core/Block/Payment/Method/Form/Creditcard.php
- app/code/community/Payone/Core/Block/Payment/Method/Info/Creditcard.php
- app/code/community/Payone/Core/Model/Mapper/ApiRequest/Payment/Authorize/Abstract.php
- app/code/community/Payone/Core/Model/Observer/Sales/Order.php
- app/design/adminhtml/default/default/template/payone/core/payment/method/form/creditcard.phtml
- app/design/adminhtml/default/default/template/payone/core/payment/method/info/creditcard.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/form/creditcard.phtml
- app/design/frontend/base/default/template/payone/core/payment/method/info/creditcard.phtml
- app/locale/de_DE/Payone_Core.csv
- app/locale/en_US/Payone_Core.csv
- js/payone/core/creditcard.js
+ add validation and translated error message
> MAGE-508 : Re-introduce CreditCardHolder field in checkout

- app/code/community/Payone/Core/Model/Observer/Checkout/Onepage/Payment/Methods.php
+ extra check to reduce triggering code portion when not necessary
Fixes #459
> MAGE-510 : remove old code and

- CHANGELOG.md
- app/code/community/Payone/Core/etc/config.xml
**New Features**
- Add Apple Pay
**Maintenance**
- Rename Payolution to Unzer
> version bump to 530

- Changelog.txt
- app/code/community/Payone/Core/etc/config.xml
Bugfix(es)
* Fix issue with creating an backofficeorder with secure invoice
Maintenance
* update the banklist in iDeal 
* tested with Magento 1.9.4.4
> version bump to 531

- Changelog.txt
- app/code/community/Payone/Core/etc/config.xml
New Features
* New Banklist for iDeal
Bugfixes
* Change error Handling for PayPal Express
* Ratepay address update
* Fix for workorderID in PayPal
* Remove Paydirekt Express
> version bump to 532
